# Generated by Django 3.2.13 on 2022-07-16 02:13

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=partners.models.upload_location, verbose_name='Photo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('name', models.TextField(max_length=55, verbose_name='name')),
            ],
        ),
    ]
