# Generated by Django 3.2.13 on 2022-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='name',
            field=models.CharField(max_length=55, verbose_name='name'),
        ),
    ]
