# Generated by Django 4.0.6 on 2022-07-17 00:03

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_partnersmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersmodel',
            name='link_en',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='link_ru',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='link_uz',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='link_zh',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='link_znc',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='logo_en',
            field=models.ImageField(null=True, upload_to=partners.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='logo_ru',
            field=models.ImageField(null=True, upload_to=partners.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='logo_uz',
            field=models.ImageField(null=True, upload_to=partners.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='logo_zh',
            field=models.ImageField(null=True, upload_to=partners.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='logo_znc',
            field=models.ImageField(null=True, upload_to=partners.models.upload_location, verbose_name='Photo'),
        ),
    ]
