# Generated by Django 4.0.6 on 2022-07-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnersmodel_link_en_partnersmodel_link_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersmodel',
            old_name='link_znc',
            new_name='link_zho',
        ),
        migrations.RenameField(
            model_name='partnersmodel',
            old_name='logo_znc',
            new_name='logo_zho',
        ),
    ]
