# Generated by Django 4.0.6 on 2022-07-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentsmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2️', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=255),
        ),
    ]
