# Generated by Django 4.0.6 on 2022-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelessonmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelessonmodel',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freelessonmodel',
            name='sex',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Gender'),
        ),
    ]
