# Generated by Django 3.2.13 on 2022-07-16 02:13

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Title')),
                ('body', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=courses.models.upload_location, verbose_name='Photo')),
            ],
        ),
    ]
