# Generated by Django 3.2.13 on 2022-07-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodels',
            name='body',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursesmodels',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
