# Generated by Django 4.0.6 on 2022-07-16 23:17

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20220715_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodels',
            name='body_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='body_ru',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='body_uz',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='body_zh',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='body_znc',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_en',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_ru',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_uz',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_zh',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_znc',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='title_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='title_znc',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
