# Generated by Django 4.0.6 on 2022-07-17 00:13

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursesmodels_body_en_coursesmodels_body_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesmodels',
            old_name='body_znc',
            new_name='body_zho',
        ),
        migrations.RenameField(
            model_name='coursesmodels',
            old_name='title_znc',
            new_name='title_zho',
        ),
        migrations.RemoveField(
            model_name='coursesmodels',
            name='image_znc',
        ),
        migrations.AddField(
            model_name='coursesmodels',
            name='image_zho',
            field=models.ImageField(null=True, upload_to=courses.models.upload_location, verbose_name='Photo'),
        ),
    ]
